import type { Project, LanguageOption, ProjectCategory, CategoryOption, Skill, TimelineItem } from "@/types"

export const specialties = ["Python", "Web", "AI", "Cloud"];

export const timelineData: TimelineItem[] = [
  // Education
  {
    title: "MS Artificial Intelligence",
    institution: "University of Texas at Austin",
    location: "Austin, TX",
    date: "Aug 2025 - Present",
    type: "education",
    logo: "logos/ut-austin.png"
  },
  {
    title: "BS Computer Engineering",
    institution: "Information Technology University",
    location: "Lahore",
    date: "Sept 2021 - Jun 2025",
    type: "education",
    logo: "logos/itu.jpg"
  },
  {
    title: "High School",
    institution: "Lahore Grammar School",
    location: "Lahore",
    date: "Sept 2019 - Feb 2021",
    type: "education",
    logo: "logos/lgs-jt.webp"
  },
  {
    title: "Secondary School Certificate",
    institution: "Beaconhouse School System",
    location: "Lahore",
    date: "Aug 2015 - Feb 2019",
    type: "education",
    logo: "logos/bss.jpeg"
  },
  {
    title: "Elementary Education",
    institution: "Islamic School of Irving",
    location: "Irving, TX",
    date: "Jun 2007 - May 2015",
    type: "education",
    logo: "logos/isi.png"
  },
  // Experience
  {
    title: "GIS Machine Learning Intern",
    institution: "Punjab IT Board",
    location: "Lahore",
    date: "Jul 2024 - Aug 2024",
    type: "experience",
    logo: "logos/pitb.png",
  },
  {
    title: "Teaching Assistant for DBMS",
    institution: "Information Technology University",
    location: "Lahore",
    date: "Jan 2025 - Jun 2025",
    type: "experience",
    logo: "logos/itu.jpg",
  },
];

export const projects: Project[] = [
  {
    title: "Pizzario: A Pizza Ordering App",
    description: "A mobile app that simulates a complete pizza ordering experience from browsing & pizza customization to checkout.",
    image: "/project-ss/pizza-app.png",
    tech: ["React Native", "Android", "Javascript", "Firebase", "OpenStreetMap"],
    github: "https://github.com/awwab-s/pizza-app",
    live: "/project-ss/pizza-app.mp4",
    category: "web-app",
    year: 2025,
  },
  {
    title: "Weather App",
    description: "A simple weather web application using OpenWeather API to fetch real-time weather & forecast for any city.",
    image: "/project-ss/weather-app.png",
    tech: ["HTML", "CSS", "Javascript", "OpenWeather API"],
    github: "https://github.com/awwab-s/weather-app",
    live: "https://weather-app-awb.vercel.app/",
    category: "web-app",
    year: 2025,
  },
  {
    title: "E-Commerce Customer Chatbot",
    description: "AI-powered customer assistance chatbot for product suggession built on OpenAI GPT-3.5 Turbo and MongoDB search.",
    image: "/project-ss/chatbot.png",
    tech: ["Python", "OpenAI", "FastAPI", "MongoDB"],
    github: "https://github.com/BSCE21002/fyp-chatbot",
    live: "#",
    category: "ai-ml",
    year: 2025,
  },
  {
    title: "NexSell: A Complete E-Commerce Platform",
    description: "A MERN stack e-commerce marketplace with store management, AI customer assistance, & elastic search.",
    image: "/project-ss/e-commerce.png",
    tech: ["Next.js", "Mongodb", "Clerk", "OpenAI", "Elastic Search", "Stripe", "Socket.io"],
    github: "https://github.com/bscw21027/final-year-project",
    live: "https://fypmarket.vercel.app/",
    category: "web-app",
    year: 2024,
  },
  {
    title: "GIS Crop Classification",
    description: "Developed ML models based on Sentinel-2 satellite data to classify crop types in the Punjab region of Pakistan.",
    image: "/project-ss/crop-classification.png",
    tech: ["Python", "Google Earth Engine", "Sentinel-2", "Random Forest", "SVM"],
    github: "#",
    live: "https://www.linkedin.com/posts/awwab-s_pitb-itu-internship-activity-7261240017593753600-rvXX?utm_source=share&utm_medium=member_desktop&rcm=ACoAADh6ckQBczZFBaT6hcBRlQ8aHGPAVps4oF4",
    category: "ai-ml",
    year: 2024,
  },
  {
    title: "Personalized Diet Recommendation System",
    description: "Developed & trained a neural network to recommend personalized diets for individuals at risk of chronic diseases.",
    image: "/project-ss/diet-prediction.png",
    tech: ["Python", "MATLAB", "Excel", "LaTex"],
    github: "https://github.com/awwab-s/Diet-Type-RecommendationSystem",
    live: "/project-ss/diet-prediction-paper.pdf",
    category: "ai-ml",
    year: 2024,
  },
  {
    title: "Iot Based Weather Monitoring System",
    description: "ESP32 based IoT system to monitor weather conditions using MQTT Broker and send data to web server.",
    image: "/project-ss/weather-monitor.png",
    tech: ["ESP32", "Arduino IDE", "C Language", "MQTTX", "PowerBI"],
    github: "#",
    live: "#",
    category: "other",
    year: 2024,
  },
  {
    title: "Game Discovery Platform",
    description: "A web platform to discover, search, and filter video games using the RAWG Video Games Database API.",
    image: "/project-ss/gamehub.png",
    tech: ["React", "TypeScript", "RAWG API"],
    github: "https://github.com/awwab-s/game-hub",
    live: "https://gamehub-awb.vercel.app/",
    category: "web-app",
    year: 2023,
  },
  {
    title: "Airline Booking Management System",
    description: "An airline booking web application where users can search & book flights and admin can manage flights & schedules.",
    image: "/project-ss/flight-booking.png",
    tech: ["HTML", "CSS", "Javascript", "Bootstrap", "PHP", "MySQL"],
    github: "https://github.com/awwab-s/Airline-Booking-Management-System/tree/main/DBMS%20Project",
    live: "#",
    category: "web-app",
    year: 2023,
  },
  {
    title: "Water Level & Temperature Monitoring System",
    description: "STM32 based embedded system to monitor water level and temperatures with battery power optimization.",
    image: "/project-ss/water-level-monitor.png",
    tech: ["Keil uVision", "STM32CubeIDE", "C Language"],
    github: "#",
    live: "https://www.youtube.com/watch?v=hP45KTkbLyo",
    category: "other",
    year: 2023,
  },
  {
    title: "Spray Bottle 3D Model",
    description: "3D model of a spray bottle made using the SOLIDWORKS software.",
    image: "/project-ss/spray-bottle.png",
    tech: ["SOLIDWORKS", "CAD", "Assembly", "3D Printing"],
    github: "#",
    live: "/project-ss/spray-bottle-3dprint.jpg",
    category: "other",
    year: 2022,
  },
  {
    title: "Hangman Game",
    description: "Custom memory allocator with garbage collection",
    image: "/project-ss/hangman.png",
    tech: ["C++", "gcc", "Makefile"],
    github: "https://github.com/awwab-s/hangman-game",
    live: "#",
    category: "cpp",
    year: 2021,
  },
  // {
  //   title: "Task Management App",
  //   description: "A collaborative task management application",
  //   image: "/project-ss/task-management-dashboard.png",
  //   tech: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
  //   github: "#",
  //   live: "#",
  //   category: "web-app",
  //   year: 2024,
  // },
  // {
  //   title: "Social Media Dashboard",
  //   description: "Analytics dashboard for social media management",
  //   image: "/project-ss/social-media-dashboard.png",
  //   tech: ["React", "D3.js", "Express", "MongoDB"],
  //   github: "#",
  //   live: "#",
  //   category: "web-app",
  //   year: 2023,
  // },
  // {
  //   title: "Real Estate Platform",
  //   description: "Property listing and management system",
  //   image: "/project-ss/real-estate-platform.png",
  //   tech: ["Next.js", "Tailwind", "Supabase", "MapBox"],
  //   github: "#",
  //   live: "#",
  //   category: "web-app",
  //   year: 2024,
  // },
  // {
  //   title: "Food Delivery App",
  //   description: "Mobile-first food ordering and delivery platform",
  //   image: "/project-ss/food-delivery-app.png",
  //   tech: ["React Native", "Firebase", "Stripe", "Google Maps"],
  //   github: "#",
  //   live: "#",
  //   category: "web-app",
  //   year: 2023,
  // },

  // {
  //   title: "Image Classification Model",
  //   description: "Deep learning model for medical image analysis",
  //   image: "/project-ss/ai-image-classification.png",
  //   tech: ["Python", "TensorFlow", "OpenCV", "Flask"],
  //   github: "#",
  //   live: "#",
  //   category: "ai-ml",
  //   year: 2024,
  // },

  // {
  //   title: "Recommendation Engine",
  //   description: "Machine learning recommendation system",
  //   image: "/project-ss/recommendation-engine.png",
  //   tech: ["Python", "Scikit-learn", "Pandas", "Redis"],
  //   github: "#",
  //   live: "#",
  //   category: "ai-ml",
  //   year: 2023,
  // },
  // {
  //   title: "Sentiment Analysis Tool",
  //   description: "Real-time social media sentiment analyzer",
  //   image: "/project-ss/sentiment-analysis.png",
  //   tech: ["Python", "NLTK", "Twitter API", "Streamlit"],
  //   github: "#",
  //   live: "#",
  //   category: "ai-ml",
  //   year: 2023,
  // },
  // {
  //   title: "Predictive Analytics Dashboard",
  //   description: "Business intelligence and forecasting platform",
  //   image: "/project-ss/predictive-analytics.png",
  //   tech: ["Python", "Prophet", "Plotly", "Django"],
  //   github: "#",
  //   live: "#",
  //   category: "ai-ml",
  //   year: 2024,
  // },

  // {
  //   title: "Memory Management System",
  //   description: "Custom memory allocator with garbage collection",
  //   image: "/project-ss/memory-management.png",
  //   tech: ["C++", "STL", "CMake", "GTest"],
  //   github: "#",
  //   live: "#",
  //   category: "cpp",
  //   year: 2023,
  // },
  // {
  //   title: "Network Protocol Implementation",
  //   description: "Custom TCP/IP stack implementation",
  //   image: "/project-ss/network-protocol.png",
  //   tech: ["C", "Socket Programming", "Linux", "Wireshark"],
  //   github: "#",
  //   live: "#",
  //   category: "cpp",
  //   year: 2023,
  // },
  // {
  //   title: "Database Engine",
  //   description: "Lightweight relational database engine",
  //   image: "/project-ss/database-engine.png",
  //   tech: ["C++", "B+ Trees", "ACID", "Multi-threading"],
  //   github: "#",
  //   live: "#",
  //   category: "cpp",
  //   year: 2024,
  // },
  // {
  //   title: "Compiler Design",
  //   description: "Custom programming language compiler",
  //   image: "/project-ss/compiler-design.png",
  //   tech: ["C++", "LLVM", "Flex", "Bison"],
  //   github: "#",
  //   live: "#",
  //   category: "cpp",
  //   year: 2024,
  // },
  // {
  //   title: "Operating System Kernel",
  //   description: "Microkernel operating system implementation",
  //   image: "/project-ss/os-kernel.png",
  //   tech: ["C", "Assembly", "QEMU", "GDB"],
  //   github: "#",
  //   live: "#",
  //   category: "cpp",
  //   year: 2023,
  // },

  // {
  //   title: "Enterprise CRM System",
  //   description: "Customer relationship management platform",
  //   image: "/project-ss/crm-system.png",
  //   tech: ["C#", "ASP.NET Core", "Entity Framework", "SQL Server"],
  //   github: "#",
  //   live: "#",
  //   category: "dotnet",
  //   year: 2024,
  // },
  // {
  //   title: "Microservices Architecture",
  //   description: "Scalable microservices with API Gateway",
  //   image: "/project-ss/microservices.png",
  //   tech: ["C#", ".NET 8", "Docker", "Kubernetes"],
  //   github: "#",
  //   live: "#",
  //   category: "dotnet",
  //   year: 2024,
  // },
  // {
  //   title: "WPF Desktop Application",
  //   description: "Rich desktop application for data visualization",
  //   image: "/project-ss/wpf-desktop.png",
  //   tech: ["C#", "WPF", "MVVM", "SQLite"],
  //   github: "#",
  //   live: "#",
  //   category: "dotnet",
  //   year: 2023,
  // },
  // {
  //   title: "Blazor Web Application",
  //   description: "Interactive web app using Blazor Server",
  //   image: "/project-ss/blazor-app.png",
  //   tech: ["C#", "Blazor", "SignalR", "Azure"],
  //   github: "#",
  //   live: "#",
  //   category: "dotnet",
  //   year: 2024,
  // },
  // {
  //   title: "REST API with Authentication",
  //   description: "Secure API with JWT authentication",
  //   image: "/project-ss/dotnet-api.png",
  //   tech: ["C#", "ASP.NET Core", "JWT", "Identity"],
  //   github: "#",
  //   live: "#",
  //   category: "dotnet",
  //   year: 2023,
  // },

  // {
  //   title: "2D Platformer Game",
  //   description: "Retro-style platformer with pixel art",
  //   image: "/project-ss/platformer-game.png",
  //   tech: ["Unity", "C#", "Pixel Art", "Audio"],
  //   github: "#",
  //   live: "#",
  //   category: "gamedev",
  //   year: 2023,
  // },
  // {
  //   title: "3D Racing Simulator",
  //   description: "Realistic car racing simulation",
  //   image: "/project-ss/racing-game.png",
  //   tech: ["Unreal Engine", "C++", "Physics", "AI"],
  //   github: "#",
  //   live: "#",
  //   category: "gamedev",
  //   year: 2024,
  // },
  // {
  //   title: "Mobile Puzzle Game",
  //   description: "Addictive puzzle game for mobile devices",
  //   image: "/project-ss/puzzle-game.png",
  //   tech: ["Unity", "C#", "Mobile", "Analytics"],
  //   github: "#",
  //   live: "#",
  //   category: "gamedev",
  //   year: 2024,
  // },
  // {
  //   title: "VR Experience",
  //   description: "Immersive virtual reality experience",
  //   image: "/project-ss/vr-experience.png",
  //   tech: ["Unity", "VR SDK", "C#", "3D Modeling"],
  //   github: "#",
  //   live: "#",
  //   category: "gamedev",
  //   year: 2024,
  // },
  // {
  //   title: "Multiplayer Strategy Game",
  //   description: "Real-time strategy game with online multiplayer",
  //   image: "/project-ss/strategy-game.png",
  //   tech: ["Godot", "GDScript", "Networking", "AI"],
  //   github: "#",
  //   live: "#",
  //   category: "gamedev",
  //   year: 2023,
  // },
]

export const skills: Skill[] = [
  { name: "HTML", logo: "/logos/html.svg" },
  { name: "CSS", logo: "/logos/css.svg" },
  { name: "JavaScript", logo: "/logos/javascript.svg", scale: "scale-90" },
  { name: "React", logo: "/logos/react.svg" },
  { name: "Next.js", logo: "/logos/nextjs.svg" },
  { name: "TypeScript", logo: "/logos/typescript.svg", scale: "scale-90" },
  { name: "Tailwind CSS", logo: "/logos/tailwindcss.svg" },
  { name: "Node.js", logo: "/logos/nodejs.svg" },
  // { name: "Express.js", logo: "/logos/express.svg" },
  // { name: "REST APIs", logo: "/logos/api.png" },
  // { name: "GraphQL", logo: "/logos/graphql.png" },
  { name: "MySQL", logo: "/logos/mysql.svg", scale: "scale-90" },
  { name: "MongoDB", logo: "/logos/mongodb.svg" },
  // { name: "PostgreSQL", logo: "/logos/postgresql.png" },
  { name: "Firebase", logo: "/logos/firebase.svg" },
  { name: "Python", logo: "/logos/python.svg" },
  { name: "Jupyter", logo: "/logos/jupyter.svg" },
  // { name: "TensorFlow", logo: "/logos/tensorflow.png" },
  { name: "PyTorch", logo: "/logos/pytorch.svg" },
  { name: "Scikit-learn", logo: "/logos/scikit-learn.svg", scale: "scale-110" },
  { name: "OpenCV", logo: "/logos/opencv.svg" },
  // // { name: "NLP", logo: "/logos/nlp.png" },
  { name: "Matlab", logo: "/logos/matlab.svg", scale: "scale-110" },
  { name: "VS Code", logo: "/logos/vscode.svg", scale: "scale-90" },
  { name: "Git", logo: "/logos/git.svg" },
  { name: "Postman", logo: "/logos/postman.svg" },
  { name: "C/C++", logo: "/logos/cpp.svg" },
  { name: "Ubuntu", logo: "/logos/ubuntu.svg" },
  { name: "Arduino", logo: "/logos/arduino.svg" },
  { name: "STM32", logo: "/logos/stm32.png" },
  { name: "ESP32", logo: "/logos/esp32.png" },
  { name: "VerilogHDL", logo: "/logos/verilog.svg"},
  { name: "Cisco Packet Tracer", logo: "/logos/cisco-packet-tracer.webp"},
  // { name: "System Design", logo: "/logos/system.png" },
  // { name: "Data Structures", logo: "/logos/datastructures.png" },
  // { name: "Algorithms", logo: "/logos/algorithms.png" },
  // { name: "Memory Management", logo: "/logos/memory.png" },
  // { name: "Multithreading", logo: "/logos/threading.png" },
  // { name: "C#", logo: "/logos/csharp.png" },
  // { name: "ASP.NET Core", logo: "/logos/dotnet.png" },
  // { name: "Entity Framework", logo: "/logos/ef.png" },
  // { name: "Blazor", logo: "/logos/blazor.png" },
  // { name: "WPF", logo: "/logos/wpf.png" },
  // { name: "Azure", logo: "/logos/azure.png" },
  { name: "Unity", logo: "/logos/unity.svg" },
  // { name: "Unreal Engine", logo: "/logos/unreal.png" },
  // { name: "3D Modeling", logo: "/logos/3d.png" },
  // { name: "Game Physics", logo: "/logos/physics.png" },
]

export const languageOptions: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "ur", name: "Urdu", nativeName: "اردو", flag: "🇵🇰" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
]

export const contactInfo = {
  email: "awwabsamad123@gmail.com",
  phone: "+92 (309) 956-3961",
  location: "Lahore",
  github: "https://github.com/awwab-s",
  linkedin: "https://www.linkedin.com/in/awwab-s/",
  instagram: "https://www.instagram.com/system.adm1n/",
}

export const projectCategories: Record<ProjectCategory, CategoryOption> = {
  "web-app": {
    name: "Web/App Dev",
    color: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
  },
  "ai-ml": {
    name: "AI/ML",
    color: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
  },
  cpp: {
    name: "C/C++",
    color: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200",
  },
  // gamedev: {
  //   name: "Game Dev",
  //   color: "bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200",
  // },
  other: {
    name: "Other",
    color: "bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200",
  },
}


export const socialLinks = [
  { name: "GitHub", url: "https://github.com/awwab-s", icon: "github" },
  { name: "LinkedIn", url: "https://www.linkedin.com/in/awwab-s/", icon: "linkedin" },
  // { name: "Twitter", url: "#", icon: "twitter" },
  { name: "Instagram", url: "https://www.instagram.com/system.adm1n/", icon: "instagram" },
]
