import type { Project, LanguageOption, ProjectCategory, CategoryOption, Skill, TimelineItem } from "@/types"

export const specialties = ["ML", "Web", "Cloud", "Mobile", "AI"];

export const timelineData: TimelineItem[] = [
  // Education
  {
    title: "MS Artificial Intelligence",
    institution: "University of Texas at Austin",
    location: "Austin, TX",
    date: "Aug 2025 - Present",
    type: "education",
    logo: "logos/ut-austin.png"
  },
  {
    title: "BS Computer Engineering",
    institution: "Information Technology University",
    location: "Lahore",
    date: "Sept 2021 - Jun 2025",
    type: "education",
    logo: "logos/itu.jpg"
  },
  {
    title: "High School",
    institution: "Lahore Grammar School",
    location: "Lahore",
    date: "Sept 2019 - Feb 2021",
    type: "education",
    logo: "logos/lgs-jt.webp"
  },
  {
    title: "Secondary School Certificate",
    institution: "Beaconhouse School System",
    location: "Lahore",
    date: "Aug 2015 - Feb 2019",
    type: "education",
    logo: "logos/bss.jpeg"
  },
  {
    title: "Elementary Education",
    institution: "Islamic School of Irving",
    location: "Irving, TX",
    date: "Jun 2007 - May 2015",
    type: "education",
    logo: "logos/isi.png"
  },
  // Experience
  {
    title: "GIS Machine Learning Intern",
    institution: "Punjab IT Board",
    location: "Lahore",
    date: "Jul 2024 - Aug 2024",
    type: "experience",
    logo: "logos/pitb.png",
  },
  {
    title: "Teaching Assistant for DBMS",
    institution: "Information Technology University",
    location: "Lahore",
    date: "Jan 2025 - Jun 2025",
    type: "experience",
    logo: "logos/itu.jpg",
  },
];

export const projects: Project[] = [
  // Web/App Development Projects
  {
    title: "E-Commerce Platform",
    description: "A full-stack e-commerce solution with payment integration",
    image: "/project-ss/modern-ecommerce-website.png",
    tech: ["React", "Node.js", "MongoDB", "Stripe"],
    github: "#",
    live: "#",
    category: "web-app",
    year: 2024,
  },
  {
    title: "Task Management App",
    description: "A collaborative task management application",
    image: "/project-ss/task-management-dashboard.png",
    tech: ["Next.js", "TypeScript", "Prisma", "PostgreSQL"],
    github: "#",
    live: "#",
    category: "web-app",
    year: 2024,
  },
  {
    title: "Social Media Dashboard",
    description: "Analytics dashboard for social media management",
    image: "/project-ss/social-media-dashboard.png",
    tech: ["React", "D3.js", "Express", "MongoDB"],
    github: "#",
    live: "#",
    category: "web-app",
    year: 2023,
  },
  {
    title: "Real Estate Platform",
    description: "Property listing and management system",
    image: "/project-ss/real-estate-platform.png",
    tech: ["Next.js", "Tailwind", "Supabase", "MapBox"],
    github: "#",
    live: "#",
    category: "web-app",
    year: 2024,
  },
  {
    title: "Food Delivery App",
    description: "Mobile-first food ordering and delivery platform",
    image: "/project-ss/food-delivery-app.png",
    tech: ["React Native", "Firebase", "Stripe", "Google Maps"],
    github: "#",
    live: "#",
    category: "web-app",
    year: 2023,
  },

  // AI/ML Projects
  {
    title: "Image Classification Model",
    description: "Deep learning model for medical image analysis",
    image: "/project-ss/ai-image-classification.png",
    tech: ["Python", "TensorFlow", "OpenCV", "Flask"],
    github: "#",
    live: "#",
    category: "ai-ml",
    year: 2024,
  },
  {
    title: "Chatbot Assistant",
    description: "AI-powered customer service chatbot",
    image: "/project-ss/ai-chatbot.png",
    tech: ["Python", "NLP", "Transformers", "FastAPI"],
    github: "#",
    live: "#",
    category: "ai-ml",
    year: 2024,
  },
  {
    title: "Recommendation Engine",
    description: "Machine learning recommendation system",
    image: "/project-ss/recommendation-engine.png",
    tech: ["Python", "Scikit-learn", "Pandas", "Redis"],
    github: "#",
    live: "#",
    category: "ai-ml",
    year: 2023,
  },
  {
    title: "Sentiment Analysis Tool",
    description: "Real-time social media sentiment analyzer",
    image: "/project-ss/sentiment-analysis.png",
    tech: ["Python", "NLTK", "Twitter API", "Streamlit"],
    github: "#",
    live: "#",
    category: "ai-ml",
    year: 2023,
  },
  {
    title: "Predictive Analytics Dashboard",
    description: "Business intelligence and forecasting platform",
    image: "/project-ss/predictive-analytics.png",
    tech: ["Python", "Prophet", "Plotly", "Django"],
    github: "#",
    live: "#",
    category: "ai-ml",
    year: 2024,
  },

  // C/C++ Projects
  {
    title: "Memory Management System",
    description: "Custom memory allocator with garbage collection",
    image: "/project-ss/memory-management.png",
    tech: ["C++", "STL", "CMake", "GTest"],
    github: "#",
    live: "#",
    category: "cpp",
    year: 2023,
  },
  {
    title: "Network Protocol Implementation",
    description: "Custom TCP/IP stack implementation",
    image: "/project-ss/network-protocol.png",
    tech: ["C", "Socket Programming", "Linux", "Wireshark"],
    github: "#",
    live: "#",
    category: "cpp",
    year: 2023,
  },
  {
    title: "Database Engine",
    description: "Lightweight relational database engine",
    image: "/project-ss/database-engine.png",
    tech: ["C++", "B+ Trees", "ACID", "Multi-threading"],
    github: "#",
    live: "#",
    category: "cpp",
    year: 2024,
  },
  {
    title: "Compiler Design",
    description: "Custom programming language compiler",
    image: "/project-ss/compiler-design.png",
    tech: ["C++", "LLVM", "Flex", "Bison"],
    github: "#",
    live: "#",
    category: "cpp",
    year: 2024,
  },
  {
    title: "Operating System Kernel",
    description: "Microkernel operating system implementation",
    image: "/project-ss/os-kernel.png",
    tech: ["C", "Assembly", "QEMU", "GDB"],
    github: "#",
    live: "#",
    category: "cpp",
    year: 2023,
  },

  // .NET Projects
  {
    title: "Enterprise CRM System",
    description: "Customer relationship management platform",
    image: "/project-ss/crm-system.png",
    tech: ["C#", "ASP.NET Core", "Entity Framework", "SQL Server"],
    github: "#",
    live: "#",
    category: "dotnet",
    year: 2024,
  },
  {
    title: "Microservices Architecture",
    description: "Scalable microservices with API Gateway",
    image: "/project-ss/microservices.png",
    tech: ["C#", ".NET 8", "Docker", "Kubernetes"],
    github: "#",
    live: "#",
    category: "dotnet",
    year: 2024,
  },
  {
    title: "WPF Desktop Application",
    description: "Rich desktop application for data visualization",
    image: "/project-ss/wpf-desktop.png",
    tech: ["C#", "WPF", "MVVM", "SQLite"],
    github: "#",
    live: "#",
    category: "dotnet",
    year: 2023,
  },
  {
    title: "Blazor Web Application",
    description: "Interactive web app using Blazor Server",
    image: "/project-ss/blazor-app.png",
    tech: ["C#", "Blazor", "SignalR", "Azure"],
    github: "#",
    live: "#",
    category: "dotnet",
    year: 2024,
  },
  {
    title: "REST API with Authentication",
    description: "Secure API with JWT authentication",
    image: "/project-ss/dotnet-api.png",
    tech: ["C#", "ASP.NET Core", "JWT", "Identity"],
    github: "#",
    live: "#",
    category: "dotnet",
    year: 2023,
  },

  // Game Development Projects
  {
    title: "2D Platformer Game",
    description: "Retro-style platformer with pixel art",
    image: "/project-ss/platformer-game.png",
    tech: ["Unity", "C#", "Pixel Art", "Audio"],
    github: "#",
    live: "#",
    category: "gamedev",
    year: 2023,
  },
  {
    title: "3D Racing Simulator",
    description: "Realistic car racing simulation",
    image: "/project-ss/racing-game.png",
    tech: ["Unreal Engine", "C++", "Physics", "AI"],
    github: "#",
    live: "#",
    category: "gamedev",
    year: 2024,
  },
  {
    title: "Mobile Puzzle Game",
    description: "Addictive puzzle game for mobile devices",
    image: "/project-ss/puzzle-game.png",
    tech: ["Unity", "C#", "Mobile", "Analytics"],
    github: "#",
    live: "#",
    category: "gamedev",
    year: 2024,
  },
  {
    title: "VR Experience",
    description: "Immersive virtual reality experience",
    image: "/project-ss/vr-experience.png",
    tech: ["Unity", "VR SDK", "C#", "3D Modeling"],
    github: "#",
    live: "#",
    category: "gamedev",
    year: 2024,
  },
  // {
  //   title: "Multiplayer Strategy Game",
  //   description: "Real-time strategy game with online multiplayer",
  //   image: "/project-ss/strategy-game.png",
  //   tech: ["Godot", "GDScript", "Networking", "AI"],
  //   github: "#",
  //   live: "#",
  //   category: "gamedev",
  //   year: 2023,
  // },
]

export const skills: Skill[] = [
  { name: "HTML", logo: "/logos/html.svg" },
  { name: "CSS", logo: "/logos/css.svg" },
  { name: "JavaScript", logo: "/logos/javascript.svg", scale: "scale-90" },
  { name: "React", logo: "/logos/react.svg" },
  { name: "Next.js", logo: "/logos/nextjs.svg" },
  { name: "TypeScript", logo: "/logos/typescript.svg", scale: "scale-90" },
  { name: "Tailwind CSS", logo: "/logos/tailwindcss.svg" },
  { name: "Node.js", logo: "/logos/nodejs.svg" },
  // { name: "Express.js", logo: "/logos/express.svg" },
  // // { name: "REST APIs", logo: "/logos/api.png" },
  // // { name: "GraphQL", logo: "/logos/graphql.png" },
  { name: "MySQL", logo: "/logos/mysql.svg", scale: "scale-90" },
  { name: "MongoDB", logo: "/logos/mongodb.svg" },
  // { name: "PostgreSQL", logo: "/logos/postgresql.png" },
  { name: "Python", logo: "/logos/python.svg" },
  { name: "Jupyter", logo: "/logos/jupyter.svg" },
  // { name: "TensorFlow", logo: "/logos/tensorflow.png" },
  { name: "PyTorch", logo: "/logos/pytorch.svg" },
  { name: "Scikit-learn", logo: "/logos/scikit-learn.svg", scale: "scale-110" },
  { name: "OpenCV", logo: "/logos/opencv.svg" },
  // // { name: "NLP", logo: "/logos/nlp.png" },
  { name: "Matlab", logo: "/logos/matlab.svg" },
  { name: "VS Code", logo: "/logos/vscode.svg", scale: "scale-90" },
  { name: "Git", logo: "/logos/git.svg" },
  { name: "Postman", logo: "/logos/postman.svg" },
  { name: "Firebase", logo: "/logos/firebase.svg" },
  { name: "C/C++", logo: "/logos/cpp.svg" },
  { name: "Ubuntu", logo: "/logos/ubuntu.svg" },
  // { name: "System Design", logo: "/logos/system.png" },
  // // { name: "Data Structures", logo: "/logos/datastructures.png" },
  // // { name: "Algorithms", logo: "/logos/algorithms.png" },
  // // { name: "Memory Management", logo: "/logos/memory.png" },
  // // { name: "Multithreading", logo: "/logos/threading.png" },
  // { name: "C#", logo: "/logos/csharp.png" },
  // // { name: "ASP.NET Core", logo: "/logos/aspnet.png" },
  // // { name: "Entity Framework", logo: "/logos/ef.png" },
  // // { name: "Blazor", logo: "/logos/blazor.png" },
  // // { name: "WPF", logo: "/logos/wpf.png" },
  // // { name: "Azure", logo: "/logos/azure.png" },
  { name: "Unity", logo: "/logos/unity.svg" },
  // // { name: "Unreal Engine", logo: "/logos/unreal.png" },
  // { name: "3D Modeling", logo: "/logos/3d.png" },
  // // { name: "Game Physics", logo: "/logos/physics.png" },
]

export const languageOptions: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "ur", name: "Urdu", nativeName: "اردو", flag: "🇵🇰" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
]

export const contactInfo = {
  email: "awwabsamad123@gmail.com",
  phone: "+92 (309) 956-3961",
  location: "Lahore",
  github: "https://github.com/awwab-s",
  linkedin: "https://www.linkedin.com/in/awwab-s/",
  instagram: "https://www.instagram.com/system.adm1n/",
}

export const projectCategories: Record<ProjectCategory, CategoryOption> = {
  "web-app": {
    name: "Web/App Dev",
    color: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
  },
  "ai-ml": {
    name: "AI/ML",
    color: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
  },
  cpp: {
    name: "C/C++",
    color: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200",
  },
  dotnet: {
    name: ".NET",
    color: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
  },
  gamedev: {
    name: "Game Dev",
    color: "bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200",
  },
}


export const socialLinks = [
  { name: "GitHub", url: "https://github.com/awwab-s", icon: "github" },
  { name: "LinkedIn", url: "https://www.linkedin.com/in/awwab-s/", icon: "linkedin" },
  { name: "Twitter", url: "#", icon: "twitter" },
  { name: "Instagram", url: "https://www.instagram.com/system.adm1n/", icon: "instagram" },
]
